/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.aisha;

/**
 *
 * @author Ajay
 */
public class AISHA_HOME extends javax.swing.JFrame {

    /**
     * Creates new form AISHA_HOME
     */
    public AISHA_HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aishaHomePanel = new javax.swing.JPanel();
        speakPanel = new javax.swing.JPanel();
        speakLabel = new javax.swing.JLabel();
        btn_speak = new javax.swing.JButton();
        newsPanel = new javax.swing.JPanel();
        newsLabel = new javax.swing.JLabel();
        btn_news = new javax.swing.JButton();
        weatherPanel = new javax.swing.JPanel();
        weatherLabel = new javax.swing.JLabel();
        btn_weather = new javax.swing.JButton();
        cirPanel = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        studentBtn = new javax.swing.JButton();
        examPanel = new javax.swing.JPanel();
        examLabel = new javax.swing.JLabel();
        btn_examUpdate = new javax.swing.JButton();
        aktuPanel = new javax.swing.JPanel();
        aktuLabel = new javax.swing.JLabel();
        btn_aktu = new javax.swing.JButton();
        eventsPanel = new javax.swing.JPanel();
        eventsLabel = new javax.swing.JLabel();
        btn_collegeEvents = new javax.swing.JButton();
        aishaHeaderPanel = new javax.swing.JPanel();
        aishaHeaderLabel = new javax.swing.JLabel();
        aisha_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AISHA Home");
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        aishaHomePanel.setPreferredSize(new java.awt.Dimension(1200, 600));
        aishaHomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        speakPanel.setBackground(new java.awt.Color(5, 19, 56));
        speakPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        speakPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        speakLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        speakLabel.setForeground(new java.awt.Color(255, 255, 255));
        speakLabel.setText("Tap to speak");
        speakPanel.add(speakLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, -1));

        btn_speak.setBackground(new java.awt.Color(1, 60, 95));
        btn_speak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Webp.net-resizeimage2.png"))); // NOI18N
        btn_speak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_speakActionPerformed(evt);
            }
        });
        speakPanel.add(btn_speak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 100));

        aishaHomePanel.add(speakPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, -1, 130));

        newsPanel.setBackground(new java.awt.Color(5, 19, 56));
        newsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newsLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        newsLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsLabel.setText("Today's News");
        newsPanel.add(newsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, -1));

        btn_news.setBackground(new java.awt.Color(1, 60, 95));
        btn_news.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/news.png"))); // NOI18N
        btn_news.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newsActionPerformed(evt);
            }
        });
        newsPanel.add(btn_news, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(newsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 150, 150));

        weatherPanel.setBackground(new java.awt.Color(5, 19, 56));
        weatherPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        weatherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weatherLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        weatherLabel.setForeground(new java.awt.Color(255, 255, 255));
        weatherLabel.setText("Weather");
        weatherPanel.add(weatherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        btn_weather.setBackground(new java.awt.Color(1, 60, 95));
        btn_weather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/weather.png"))); // NOI18N
        btn_weather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_weatherActionPerformed(evt);
            }
        });
        weatherPanel.add(btn_weather, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(weatherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, -1));

        cirPanel.setBackground(new java.awt.Color(5, 19, 56));
        cirPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        cirPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentLabel.setText(" Student Details");
        cirPanel.add(studentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        studentBtn.setBackground(new java.awt.Color(1, 60, 95));
        studentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/notification.png"))); // NOI18N
        studentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBtnActionPerformed(evt);
            }
        });
        cirPanel.add(studentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(cirPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        examPanel.setBackground(new java.awt.Color(5, 19, 56));
        examPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        examPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        examLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        examLabel.setForeground(new java.awt.Color(255, 255, 255));
        examLabel.setText("Exam Update");
        examPanel.add(examLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btn_examUpdate.setBackground(new java.awt.Color(1, 60, 95));
        btn_examUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/exam_update.png"))); // NOI18N
        btn_examUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examUpdateActionPerformed(evt);
            }
        });
        examPanel.add(btn_examUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(examPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        aktuPanel.setBackground(new java.awt.Color(5, 19, 56));
        aktuPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        aktuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aktuLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        aktuLabel.setForeground(new java.awt.Color(255, 255, 255));
        aktuLabel.setText("AKTU Update");
        aktuPanel.add(aktuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        btn_aktu.setBackground(new java.awt.Color(1, 60, 95));
        btn_aktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/aktu.png"))); // NOI18N
        btn_aktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktuActionPerformed(evt);
            }
        });
        aktuPanel.add(btn_aktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(aktuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        eventsPanel.setBackground(new java.awt.Color(5, 19, 56));
        eventsPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        eventsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventsLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        eventsLabel.setForeground(new java.awt.Color(255, 255, 255));
        eventsLabel.setText("College Events");
        eventsPanel.add(eventsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_collegeEvents.setBackground(new java.awt.Color(1, 60, 95));
        btn_collegeEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/events.png"))); // NOI18N
        btn_collegeEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_collegeEventsActionPerformed(evt);
            }
        });
        eventsPanel.add(btn_collegeEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 110));

        aishaHomePanel.add(eventsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        aishaHeaderPanel.setBackground(new java.awt.Color(5, 19, 56));
        aishaHeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aishaHeaderLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        aishaHeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        aishaHeaderLabel.setText("AISHA(Voice Based Personal Assistant)");
        aishaHeaderPanel.add(aishaHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 90));

        aishaHomePanel.add(aishaHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 620, 90));

        aisha_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/AISHA_Background.jpg"))); // NOI18N
        aishaHomePanel.add(aisha_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aishaHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aishaHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_weatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_weatherActionPerformed
        // TODO add your handling code here:
        AishaWeather aw=new AishaWeather();
        aw.setVisible(true);
    }//GEN-LAST:event_btn_weatherActionPerformed

    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed
        // TODO add your handling code here:
        StudentDetails circular=new StudentDetails();
        circular.setVisible(true);
    }//GEN-LAST:event_studentBtnActionPerformed

    private void btn_aktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktuActionPerformed
        // TODO add your handling code here:
        AktuUpdates aktu=new AktuUpdates();
        aktu.setVisible(true);
    }//GEN-LAST:event_btn_aktuActionPerformed

    private void btn_newsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newsActionPerformed
        // TODO add your handling code here:
        AishaNews aishaNews=new AishaNews();
        aishaNews.setVisible(true);
    }//GEN-LAST:event_btn_newsActionPerformed

    private void btn_examUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examUpdateActionPerformed
        // TODO add your handling code here:
        ExamUpdates examUpdate=new ExamUpdates();
        examUpdate.setVisible(true);
    }//GEN-LAST:event_btn_examUpdateActionPerformed

    private void btn_collegeEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_collegeEventsActionPerformed
        // TODO add your handling code here:
        CollegeEvents collegeEvent = new CollegeEvents();
        collegeEvent.setVisible(true);
    }//GEN-LAST:event_btn_collegeEventsActionPerformed

    private void btn_speakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_speakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_speakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AISHA_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AISHA_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AISHA_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AISHA_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AISHA_HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aishaHeaderLabel;
    private javax.swing.JPanel aishaHeaderPanel;
    private javax.swing.JPanel aishaHomePanel;
    private javax.swing.JLabel aisha_background;
    private javax.swing.JLabel aktuLabel;
    private javax.swing.JPanel aktuPanel;
    private javax.swing.JButton btn_aktu;
    private javax.swing.JButton btn_collegeEvents;
    private javax.swing.JButton btn_examUpdate;
    private javax.swing.JButton btn_news;
    private javax.swing.JButton btn_speak;
    private javax.swing.JButton btn_weather;
    private javax.swing.JPanel cirPanel;
    private javax.swing.JLabel eventsLabel;
    private javax.swing.JPanel eventsPanel;
    private javax.swing.JLabel examLabel;
    private javax.swing.JPanel examPanel;
    private javax.swing.JLabel newsLabel;
    private javax.swing.JPanel newsPanel;
    private javax.swing.JLabel speakLabel;
    private javax.swing.JPanel speakPanel;
    private javax.swing.JButton studentBtn;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JLabel weatherLabel;
    private javax.swing.JPanel weatherPanel;
    // End of variables declaration//GEN-END:variables
}
