/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.aisha;

/**
 *
 * @author Ajay
 */
public class AishaWeather extends javax.swing.JFrame {

    /**
     * Creates new form AishaWeather
     */
    public AishaWeather() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempLabel = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        headerLabel1 = new javax.swing.JLabel();
        monLabel = new javax.swing.JLabel();
        tueLabel = new javax.swing.JLabel();
        wedLabel = new javax.swing.JLabel();
        thursLabel = new javax.swing.JLabel();
        friLabel = new javax.swing.JLabel();
        satLabel = new javax.swing.JLabel();
        sunLabel = new javax.swing.JLabel();
        monIconLabel = new javax.swing.JLabel();
        tueIconLabel = new javax.swing.JLabel();
        wedIconLabel = new javax.swing.JLabel();
        thurIconLabel = new javax.swing.JLabel();
        friIconLabel = new javax.swing.JLabel();
        satIconLabel = new javax.swing.JLabel();
        sunIconLabel = new javax.swing.JLabel();
        headerIconLabel1 = new javax.swing.JLabel();
        hearedIconLabel = new javax.swing.JLabel();
        headerTempDescLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forecast");
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tempLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        tempLabel.setForeground(new java.awt.Color(255, 255, 255));
        tempLabel.setText("18º C");
        getContentPane().add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        headerLabel.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Noida, India");
        getContentPane().add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 150, 60));

        headerLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel1.setText("Weather Forecast");
        getContentPane().add(headerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 40));

        monLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        monLabel.setForeground(new java.awt.Color(255, 255, 255));
        monLabel.setText("Monday");
        getContentPane().add(monLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        tueLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tueLabel.setForeground(new java.awt.Color(255, 255, 255));
        tueLabel.setText("Tuesday");
        getContentPane().add(tueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        wedLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        wedLabel.setForeground(new java.awt.Color(255, 255, 255));
        wedLabel.setText("Wednesday");
        getContentPane().add(wedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        thursLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        thursLabel.setForeground(new java.awt.Color(255, 255, 255));
        thursLabel.setText("Thursday");
        getContentPane().add(thursLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        friLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        friLabel.setForeground(new java.awt.Color(255, 255, 255));
        friLabel.setText("Friday");
        getContentPane().add(friLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        satLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        satLabel.setForeground(new java.awt.Color(255, 255, 255));
        satLabel.setText("Saturday");
        getContentPane().add(satLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        sunLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sunLabel.setForeground(new java.awt.Color(255, 255, 255));
        sunLabel.setText("Sunday");
        getContentPane().add(sunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 80, -1));

        monIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        monIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        monIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Rainy.png"))); // NOI18N
        getContentPane().add(monIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        tueIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tueIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        tueIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/PartilyCloud.png"))); // NOI18N
        getContentPane().add(tueIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        wedIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        wedIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        wedIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Sunny.png"))); // NOI18N
        getContentPane().add(wedIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        thurIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        thurIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        thurIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Sunny.png"))); // NOI18N
        getContentPane().add(thurIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        friIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        friIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        friIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/PartilyCloud.png"))); // NOI18N
        getContentPane().add(friIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        satIconLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        satIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        satIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Rainy.png"))); // NOI18N
        getContentPane().add(satIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        sunIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Sunny.png"))); // NOI18N
        getContentPane().add(sunIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        headerIconLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/weather.png"))); // NOI18N
        headerIconLabel1.setText("jLabel6");
        getContentPane().add(headerIconLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 160));

        hearedIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Sunny.png"))); // NOI18N
        getContentPane().add(hearedIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        headerTempDescLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerTempDescLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerTempDescLabel.setText("Sunny");
        getContentPane().add(headerTempDescLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        backgroundLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backgroundLabel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/Weather_1.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AishaWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AishaWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AishaWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AishaWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AishaWeather().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel friIconLabel;
    private javax.swing.JLabel friLabel;
    private javax.swing.JLabel headerIconLabel1;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JLabel headerTempDescLabel;
    private javax.swing.JLabel hearedIconLabel;
    private javax.swing.JLabel monIconLabel;
    private javax.swing.JLabel monLabel;
    private javax.swing.JLabel satIconLabel;
    private javax.swing.JLabel satLabel;
    private javax.swing.JLabel sunIconLabel;
    private javax.swing.JLabel sunLabel;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel thurIconLabel;
    private javax.swing.JLabel thursLabel;
    private javax.swing.JLabel tueIconLabel;
    private javax.swing.JLabel tueLabel;
    private javax.swing.JLabel wedIconLabel;
    private javax.swing.JLabel wedLabel;
    // End of variables declaration//GEN-END:variables
}
