/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.aisha;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ajay
 */
public class AISHA_Admin extends javax.swing.JFrame {

    /**
     * Creates new form AISHA_Admin
     */
    Connection con;
    PreparedStatement ps;    
    public AISHA_Admin() {
        initComponents();
        try { 
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "ajay","kanpur");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AISHA_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        cancleBtn = new javax.swing.JButton();
        signInBtn = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(5, 19, 56));
        homePanel.setPreferredSize(new java.awt.Dimension(1200, 600));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/aisha/images/collegeEvent.jpg"))); // NOI18N
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        passLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Password :");
        homePanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        headerLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Admin Panel");
        homePanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username :");
        homePanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));
        homePanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 210, 40));

        cancleBtn.setBackground(new java.awt.Color(1, 60, 95));
        cancleBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancleBtn.setText("cancle");
        homePanel.add(cancleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 90, 40));

        signInBtn.setBackground(new java.awt.Color(1, 60, 95));
        signInBtn.setForeground(new java.awt.Color(255, 255, 255));
        signInBtn.setText("sign in");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        homePanel.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 90, 40));

        passField.setText("jPasswordField1");
        homePanel.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 210, 40));

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        String username1=usernameField.getText().trim();
        String pass1=new String(passField.getPassword()).trim();
        try {
            ps=con.prepareStatement("select * from AishaAdmin where username = ? and pass=?");
            ps.setString(1,username1);
            ps.setString(2,pass1);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {   
                //AishaWeather aishaWeather = new AishaWeather();
                //aishaWeather.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please enter a valid username and password");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AISHA_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_signInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AISHA_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AISHA_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AISHA_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AISHA_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AISHA_Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleBtn;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton signInBtn;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
